- hosts: all
  tasks:
  - file:
      state: directory
      path: "/dvd1"

  - mount:
      src: "/dev/cdrom"
      path: "/dvd1"
      state: mounted
      fstype: "iso9660"

  - yum_repository:
      baseurl: "/dvd1/AppStream"
      name: "mydvd1"
      description: "DVD1 package"
      gpgcheck: no

  - yum_repository:
      baseurl: "/dvd1/BaseOS"
      name: "mydvd2"
      description: "DVD2 package"
      gpgcheck: no

  - name: Copying Hadoop software
    copy:
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"
      dest: "/root"


  - name: Copying JDK software
    copy:
      src: "/root/jdk-8u171-linux-x64.rpm"
      dest: "/root/"

  - name: Installing JDK
    yum:
      name: "/root/jdk-8u171-linux-x64.rpm"
      state: present
      disable_gpg_check: yes

  - name: Checking if Hadoop S/W is present or Not
    command: "hadoop version"
    register: x
    ignore_errors: yes

  - name: Installing Hadoop
    command: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm --force"
    when: x.rc!=0

- hosts: Hadoop_Master
  vars_files:
      - variables.yml
  tasks:

  - name: Creating a directory for Name Node
    file:
      state: directory
      path: "{{ nn_dir }}"

  - name: Creating "hdfs-site.xml" file
    template:
      src: "/root/ansible-ws/hdfs_master.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - name: Creating "core-site.xml" file
    template:
      src: "/root/ansible-ws/core_master.xml"
      dest: "/etc/hadoop/core-site.xml"

  - name: Adding a rule for the firewall
    firewalld:
      port: "{{ port_no }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - name: Prompting the user to format
    pause:
      prompt: "Do you want to format(y/n)?"
    register: z

  - name: Formatting the folder created for Name Node
    shell: "echo Y | hadoop namenode -format"
    when: z.user_input == "y"

  - name: Starting Name Node Services
    command: "hadoop-daemon.sh start namenode"

  - debug:
      msg: "NameNode has been successfully configured!"


- hosts: Hadoop_Slave
  vars_files:
      - variables.yml
  tasks:

  - name: Creating a directory for Data Node
    file:
      state: directory
      path: "{{ dn_dir }}"

  - name: Creating "hdfs-site.xml" file
    template:
      src: "/root/ansible-ws/hdfs_master.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - name: Creating "core-site.xml" file
    template:
      src: "/root/ansible-ws/core_master.xml"
      dest: "/etc/hadoop/core-site.xml"

  - name: Adding a rule for the firewall
    firewalld:
      port: "{{ port_no }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - name: Starting Data Node Services
    command: "hadoop-daemon.sh start datanode"

  - debug:
      msg: "DataNode has been successfully configured!"



